### ISSUE TITLE
App crashing on android

### ISSUE THREAD

**Issue by alan2030** [emostar/flutter-zendesk#31]
When I am trying to start Zendesk, my app keeps crashing 
```
E/AndroidRuntime(27925): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vivaleisure.clublime_member/zendesk.messaging.MessagingActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(27925):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
E/AndroidRuntime(27925):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
E/AndroidRuntime(27925):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(27925):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(27925):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(27925):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
E/AndroidRuntime(27925):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27925):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(27925):        at android.app.ActivityThread.main(ActivityThread.java:7099)
E/AndroidRuntime(27925):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27925):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(27925):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/AndroidRuntime(27925): Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(27925): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(27925): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(27925):        at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime(27925):        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.createView(LayoutInflater.java:686)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.inflate(LayoutInflater.java:531)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
E/AndroidRuntime(27925):        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
E/AndroidRuntime(27925):        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
E/AndroidRuntime(27925):        at zendesk.messaging.MessagingActivity.onCreate(MessagingActivity.java:121)
E/AndroidRuntime(27925):        at android.app.Activity.performCreate(Activity.java:7327)
E/AndroidRuntime(27925):        at android.app.Activity.performCreate(Activity.java:7318)
E/AndroidRuntime(27925):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
E/AndroidRuntime(27925):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
E/AndroidRuntime(27925):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
E/AndroidRuntime(27925):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(27925):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(27925):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(27925):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
E/AndroidRuntime(27925):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27925):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(27925):        at android.app.ActivityThread.main(ActivityThread.java:7099)
E/AndroidRuntime(27925):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27925):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(27925):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/AndroidRuntime(27925): Caused by: android.view.InflateException: Binary XML file line #13: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x7f040003 a=-1}
E/AndroidRuntime(27925): Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x7f040003 a=-1}
E/AndroidRuntime(27925):        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:731)
E/AndroidRuntime(27925):        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:8387)
E/AndroidRuntime(27925):        at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:439)
E/AndroidRuntime(27925):        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:370)
E/AndroidRuntime(27925):        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:56)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:904)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:863)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:905)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.inflate(LayoutInflater.java:528)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
E/AndroidRuntime(27925):        at zendesk.messaging.ui.MessagingView.<init>(MessagingView.java:49)
E/AndroidRuntime(27925):        at zendesk.messaging.ui.MessagingView.<init>(MessagingView.java:41)
E/AndroidRuntime(27925):        at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime(27925):        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.createView(LayoutInflater.java:686)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:829)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.inflate(LayoutInflater.java:531)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.inflate(LayoutInflater.java:461)
E/AndroidRuntime(27925):        at android.view.LayoutInflater.inflate(LayoutInflater.java:383)
E/AndroidRuntime(27925):        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
E/AndroidRuntime(27925):        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
E/AndroidRuntime(27925):        at zendesk.messaging.MessagingActivity.onCreate(MessagingActivity.java:121)
E/AndroidRuntime(27925):        at android.app.Activity.performCreate(Activity.java:7327)
E/AndroidRuntime(27925):        at android.app.Activity.performCreate(Activity.java:7318)
E/AndroidRuntime(27925):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
E/AndroidRuntime(27925):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
E/AndroidRuntime(27925):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3266)
E/AndroidRuntime(27925):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(27925):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(27925):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(27925):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1957)
E/AndroidRuntime(27925):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(27925):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(27925):        at android.app.ActivityThread.main(ActivityThread.java:7099)
E/AndroidRuntime(27925):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27925):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(27925):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
I/Process (27925): Sending signal. PID: 27925 SIG: 9
Lost connection to device.
```

Last version used to work perfectly. I wonder if I am the only one experiencing the issue.

**Comment by hussamDana92** [comment]
same issue

**Comment by gbuah** [comment]
I also have the same issue.... Any fix?

**Comment by kharisazhar** [comment]
Same issue on zendesk: ^2.0.0

**Comment by kharisazhar** [comment]
Hello, 

Finally i have solution of this issue crash 😬 


Add style theme on your AndroidManifest.xml

```
<manifest ....

 <application
        ........
        android:theme="@style/Theme.AppCompat">
        >
```

Thanks

**Comment by gikwegbu** [comment]
Life saver 😋
