### ISSUE TITLE
PlatformException(channel-error, Unable to establish connection on channel., null, null)

### ISSUE THREAD

**Issue by emren** [emostar/flutter-zendesk#34]
Dear Zendesk,
We are trying to run your package on IOS real device but we are getting the following error.
Can you please advise us on this issue
Thank you

[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
[        ] #0      ProfileApi.setVisitorInfo (package:zendesk/src/pigeon.dart:230:7)
[        ] <asynchronous suspension>
[        ] #1      Zendesk.setVisitorInfo (package:zendesk/src/zendesk.dart:32:5)
[        ] <asynchronous suspension>
[        ] [VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: PlatformException(channel-error, Unable to establish connection on channel., null, null)
[        ] #0      ProfileApi.addVisitorTags (package:zendesk/src/pigeon.dart:252:7)
[        ] <asynchronous suspension>
[        ] #1      Zendesk.addVisitorTags (package:zendesk/src/zendesk.dart:37:5)
[        ] <asynchronous suspension>

**Comment by canturkay** [comment]
I'm facing the same issue, are there any updates?

**Comment by IanWambai** [comment]
Same here any updates?

**Comment by IanWambai** [comment]
I was able to fix this by setting the proper Account Key.

**Comment by emren** [comment]
We have android and ios versions of our app. On android it works fine. On Ios we receive this error. We are using the same key for android and ios. Do we need separate keys for android and ios?

**Comment by Jamesweng** [comment]
Same here, any updates?

**Comment by kharisazhar** [comment]
Same here any updates? 👀

**Comment by kharisazhar** [comment]
Finally i found this solution : 


Cause : 

`PlatformException(channel-error, Unable to establish connection on channel., null, null)`

issue from 

```
zendesk
                      .setVisitorInfo(
                    name: 'My Name',
                    phoneNumber: '323-555-1212',
                  )
                      .then((r) {
                    print('setVisitorInfo finished');
                  }).catchError((e) {
                    print('error $e');
                  });
```

in my case start chat zendesk blocked by 

```
zendesk
                      .setVisitorInfo(
                    name: 'My Name',
                    phoneNumber: '323-555-1212',
                  )
                      .then((r) {
    zendesk.startChat(
                  }).catchError((e) {
                    print('error $e');
                  });
```

so the solution is separate setVisitorInfo and startChat

```
zendesk
                      .setVisitorInfo(
                    name: 'My Name',
                    phoneNumber: '323-555-1212',
                  )
                      .then((r) {
                    print('setVisitorInfo finished');
                  }).catchError((e) {
                    print('error $e');
                  });
```

```
RaisedButton(
                  child: Text('Start Chat (styled)'),
                  onPressed: () async {
                    zendesk
                        .startChat(
                      iosNavigationBarColor: Colors.red,
                      iosNavigationTitleColor: Colors.yellow,
                    )
                        .then((r) {
                      print('startChat finished');
                    }).catchError((e) {
                      print('error $e');
                    });
                  },
                ),
```

Thanks

**Comment by bhagyashreekhatri** [comment]
@kharisazhar  still the above solution which u provided is not working. Issue still persist for iOS Real device

**Comment by theakanfecode1** [comment]
Any update on this error please?

**Comment by kharisazhar** [comment]
@bhagyashreekhatri @theakanfecode1 

can you show your code please ?

in my case, i just separte setVisitor info with startZendesk : 

**or you can try, just set startZendesk :** (because visitor info is provided by Zendesk V2 Chat Bot, before connect with agent, zendesk will be ask your name and phone)

`zendesk
                        .startChat(
                      iosNavigationBarColor: Colors.red,
                      iosNavigationTitleColor: Colors.yellow,
                    )
                        .then((r) {
                      print('startChat finished');
                    }).catchError((e) {
                      print('error $e');
                    });`
